<div data-content-type="row" data-appearance="contained" data-element="main">
    <div data-enable-parallax="0" data-parallax-speed="0.5" data-background-images="{}" data-element="inner"
         style="justify-content: flex-start; display: flex; flex-direction: column; background-position: left top; background-size: cover; background-repeat: no-repeat; background-attachment: scroll; border-style: none; border-width: 1px; border-radius: 0px; margin: 0px 0px 10px; padding: 10px;">
        <figure class="image" data-content-type="image" data-appearance="full-width" data-element="main"
                style="margin: 0px; padding: 0px; border-style: none;"><a
                    href="{{widget type='Magento\Catalog\Block\Product\Widget\Link' id_path='product/1' template='Magento_PageBuilder::widget/link_href.phtml' type_name='Catalog Product Link' }}"
                    target="_blank" data-link-type="product" title="SEO TITLE" data-element="link"><img
                        class="pagebuilder-mobile-hidden" src="{{media url=wysiwyg/1547204731_baner_oprawy_3.png}}"
                        alt="SEO TEXT" title="SEO TITLE" data-element="desktop_image"
                        style="border-style: none; border-width: 1px; border-radius: 0px; max-width: 100%; height: auto;"><img
                        class="pagebuilder-mobile-only" src="{{media url=wysiwyg/full_width_banner_5.jpg}}"
                        alt="SEO TEXT" title="SEO TITLE" data-element="mobile_image"
                        style="border-style: none; border-width: 1px; border-radius: 0px; max-width: 100%; height: auto;"></a>
            <figcaption data-element="caption">Image caption</figcaption>
        </figure>
    </div>
</div>
<div data-content-type="row" data-appearance="contained" data-element="main">
    <div data-enable-parallax="0" data-parallax-speed="0.5" data-background-images="{}" data-element="inner"
         style="justify-content: flex-start; display: flex; flex-direction: column; background-position: left top; background-size: cover; background-repeat: no-repeat; background-attachment: scroll; border-style: none; border-width: 1px; border-radius: 0px; margin: 0px 0px 10px; padding: 10px;">
        <figure class="class__image__agata" data-content-type="image" data-appearance="full-width" data-element="main"
                style="text-align: left; margin: 0px; padding: 0px; border-style: none;"><a href="www.divante.pl"
                                                                                            target=""
                                                                                            data-link-type="default"
                                                                                            title="title attribute  image"
                                                                                            data-element="link">
                <img class="pagebuilder-mobile-hidden"
                     src="{{media url=wysiwyg/1494578159_1487860495_kamila_3_4.jpg}}" alt="alternative text"
                     title="title attribute  image" data-element="desktop_image"
                     style="border-style: dashed; border-width: 1px; border-radius: 0px; max-width: 100%; height: auto;">
                <img class="pagebuilder-mobile-only" src="{{media url=wysiwyg/1494578159_1487860495_kamila_3_4.jpg}}"
                     alt="alternative text" title="title attribute  image" data-element="mobile_image"
                     style="border-style: dashed; border-width: 1px; border-radius: 0px; max-width: 100%; height: auto;">
            </a>
            <figcaption data-element="caption">image caption</figcaption>
        </figure>
    </div>
</div>
<div data-content-type="row" data-appearance="contained" data-element="main">
    <div data-enable-parallax="0" data-parallax-speed="0.5" data-background-images="{}" data-element="inner"
         style="justify-content: flex-start; display: flex; flex-direction: column; background-position: left top; background-size: cover; background-repeat: no-repeat; background-attachment: scroll; border-style: none; border-width: 1px; border-radius: 0px; margin: 0px 0px 10px; padding: 10px;">
        <figure data-content-type="image" data-appearance="full-width" data-element="main"
                style="margin: 0px; padding: 0px; border-style: none;"><img class="pagebuilder-mobile-hidden"
                                                                            src="{{media url=wysiwyg/1529585052_okazje-banner_4.jpg}}"
                                                                            alt="" title="" data-element="desktop_image"
                                                                            style="border-style: none; border-width: 1px; border-radius: 0px; max-width: 100%; height: auto;"><img
                    class="pagebuilder-mobile-only" src="{{media url=wysiwyg/1529585052_okazje-banner_4.jpg}}" alt=""
                    title="" data-element="mobile_image"
                    style="border-style: none; border-width: 1px; border-radius: 0px; max-width: 100%; height: auto;">
        </figure>
    </div>
</div>
