<div data-content-type="row" data-appearance="contained" data-element="main">
    <div data-enable-parallax="0" data-parallax-speed="0.5" data-background-images="{}" data-element="inner"
         style="justify-content: flex-start; display: flex; flex-direction: column; background-position: left top; background-size: cover; background-repeat: no-repeat; background-attachment: scroll; border-style: none; border-width: 1px; border-radius: 0px; margin: 0px 0px 10px; padding: 10px;">
        <div data-content-type="banner" data-appearance="poster" data-show-button="hover" data-show-overlay="always"
             data-element="main" style="margin: 0px;"><a
                    href="{{widget type='Magento\Cms\Block\Widget\Page\Link' page_id='4' template='Magento_PageBuilder::widget/link_href.phtml' type_name='CMS Page Link' }}"
                    target="" data-link-type="page" data-element="link">
                <div class="pagebuilder-banner-wrapper"
                     data-background-images="{\&quot;desktop_image\&quot;:\&quot;{{media url=wysiwyg/1529585052_okazje-banner_2.jpg}}\&quot;}"
                     data-element="wrapper"
                     style="background-position: left top; background-size: contain; background-repeat: repeat; background-attachment: scroll; border-style: none; border-width: 1px; border-radius: 0px;">
                    <div class="pagebuilder-overlay pagebuilder-poster-overlay" data-overlay-color=""
                         data-element="overlay"
                         style="border-radius: 0px; min-height: 300px; background-color: transparent; padding: 40px;">
                        <div class="pagebuilder-poster-content">
                            <div data-element="content"><p>KONTENT MESSAGE TEXT I TAKIE TAM</p></div>
                            <button type="button" class="pagebuilder-banner-button pagebuilder-button-primary"
                                    data-element="button" style="opacity: 0; visibility: hidden;">BUTTON primary on
                                hover
                            </button>
                        </div>
                    </div>
                </div>
            </a></div>
    </div>
</div>
<div data-content-type="row" data-appearance="full-width" data-enable-parallax="0" data-parallax-speed="0.5"
     data-background-images="{}" data-element="main"
     style="justify-content: flex-start; display: flex; flex-direction: column; background-position: left top; background-size: cover; background-repeat: no-repeat; background-attachment: scroll; border-style: none; border-width: 1px; border-radius: 0px; margin: 0px 0px 10px; padding: 10px;">
    <div class="row-full-width-inner" data-element="inner">
        <div data-content-type="banner" data-appearance="poster" data-show-button="always" data-show-overlay="never"
             data-element="main" style="margin: 0px;">
            <div data-element="empty_link">
                <div class="pagebuilder-banner-wrapper"
                     data-background-images="{\&quot;desktop_image\&quot;:\&quot;{{media url=wysiwyg/1494578159_1487860495_kamila_3_2.jpg}}\&quot;,\&quot;mobile_image\&quot;:\&quot;{{media url=wysiwyg/1529585052_okazje-banner.jpg}}\&quot;}"
                     data-element="wrapper"
                     style="background-position: left top; background-size: cover; background-repeat: no-repeat; background-attachment: scroll; border-style: none; border-width: 1px; border-radius: 0px;">
                    <div class="pagebuilder-overlay pagebuilder-poster-overlay" data-overlay-color=""
                         data-element="overlay"
                         style="border-radius: 0px; min-height: 300px; background-color: transparent; padding: 40px;">
                        <div class="pagebuilder-poster-content">
                            <div data-element="content">
                                <div>&nbsp;Text on banner</div>
                                <div></div>
                            </div>
                            <button type="button" class="pagebuilder-banner-button pagebuilder-button-secondary"
                                    data-element="button" style="opacity: 1; visibility: visible;">button secondary
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div data-content-type="row" data-appearance="contained" data-element="main">
    <div data-enable-parallax="0" data-parallax-speed="0.5" data-background-images="{}" data-element="inner"
         style="justify-content: flex-start; display: flex; flex-direction: column; background-position: left top; background-size: cover; background-repeat: no-repeat; background-attachment: scroll; border-style: none; border-width: 1px; border-radius: 0px; margin: 0px 0px 10px; padding: 10px;">
        <div data-content-type="banner" data-appearance="poster" data-show-button="always" data-show-overlay="never"
             data-element="main" style="margin: 0px;">
            <div data-element="empty_link">
                <div class="pagebuilder-banner-wrapper"
                     data-background-images="{\&quot;desktop_image\&quot;:\&quot;{{media url=wysiwyg/1529585052_okazje-banner_3.jpg}}\&quot;}"
                     data-element="wrapper"
                     style="background-position: left top; background-size: cover; background-repeat: no-repeat; background-attachment: scroll; border-style: none; border-width: 1px; border-radius: 0px;">
                    <div class="pagebuilder-overlay pagebuilder-poster-overlay" data-overlay-color=""
                         data-element="overlay"
                         style="border-radius: 0px; min-height: 300px; background-color: transparent; padding: 40px;">
                        <div class="pagebuilder-poster-content">
                            <div data-element="content"></div>
                            <button type="button" class="pagebuilder-banner-button pagebuilder-button-link"
                                    data-element="button" style="opacity: 1; visibility: visible;">Button LINK
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div data-content-type="row" data-appearance="contained" data-element="main">
    <div data-enable-parallax="0" data-parallax-speed="0.5" data-background-images="{}" data-element="inner"
         style="justify-content: flex-start; display: flex; flex-direction: column; background-position: left top; background-size: cover; background-repeat: no-repeat; background-attachment: scroll; border-style: none; border-width: 1px; border-radius: 0px; margin: 0px 0px 10px; padding: 10px;">
        <div data-content-type="banner" data-appearance="poster" data-show-button="always" data-show-overlay="never"
             data-element="main" style="margin: 0px;">
            <div data-element="empty_link">
                <div class="pagebuilder-banner-wrapper"
                     data-background-images="{\&quot;desktop_image\&quot;:\&quot;{{media url=wysiwyg/full_width_banner_6.jpg}}\&quot;}"
                     data-element="wrapper"
                     style="background-position: left top; background-size: cover; background-repeat: no-repeat; background-attachment: scroll; border-style: none; border-width: 1px; border-radius: 0px;">
                    <div class="pagebuilder-overlay pagebuilder-poster-overlay" data-overlay-color=""
                         data-element="overlay"
                         style="border-radius: 0px; min-height: 300px; background-color: transparent; padding: 40px;">
                        <div class="pagebuilder-poster-content">
                            <div data-element="content"></div>
                            <button type="button" class="pagebuilder-banner-button pagebuilder-button-primary"
                                    data-element="button" style="opacity: 1; visibility: visible;">NO BUTTON LINK
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
