<div data-content-type="row" data-appearance="contained" data-element="main">
    <div data-enable-parallax="0" data-parallax-speed="0.5" data-background-images="{}" data-element="inner"
         style="justify-content: flex-start; display: flex; flex-direction: column; background-position: left top; background-size: cover; background-repeat: no-repeat; background-attachment: scroll; border-style: none; border-width: 1px; border-radius: 0px; margin: 0px 0px 10px; padding: 10px;">
        <div class="pagebuilder-slider" data-content-type="slider" data-appearance="default" data-autoplay="true"
             data-autoplay-speed="4000" data-fade="true" data-infinite-loop="true" data-show-arrows="true"
             data-show-dots="true" data-element="main"
             style="text-align: left; min-height: 300px; border-style: none; border-width: 1px; border-radius: 0px; margin: 0px; padding: 0px;">
            <div data-content-type="slide" data-slide-name="Slide name" data-appearance="poster"
                 data-show-button="never" data-show-overlay="never" data-element="main" style="margin: 0px;">
                <div data-element="empty_link">
                    <div class="pagebuilder-slide-wrapper"
                         data-background-images="{\&quot;desktop_image\&quot;:\&quot;https://magento2ee.test/pub/media/wysiwyg/1529585052_okazje-banner.jpg\&quot;}"
                         data-element="wrapper"
                         style="background-position: left top; background-size: cover; background-repeat: no-repeat; border-style: none; border-width: 1px; border-radius: 0px; min-height: 300px;">
                        <div class="pagebuilder-overlay pagebuilder-poster-overlay" data-overlay-color=""
                             data-element="overlay"
                             style="min-height: 300px; padding: 40px; background-color: transparent;">
                            <div class="pagebuilder-poster-content">
                                <div data-element="content">
                                    <div><span style="color: #ff6600;">&nbsp;TEKST NA BANNERZE - CONTENT ?&nbsp;</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div data-content-type="slide" data-slide-name="Slide 2" data-appearance="collage-right"
                 data-show-button="always" data-show-overlay="never" data-element="main" style="margin: 0px;"><a
                        href="www.divante.pl" target="" data-link-type="default" data-element="link">
                    <div class="pagebuilder-slide-wrapper"
                         data-background-images="{\&quot;desktop_image\&quot;:\&quot;https://magento2ee.test/pub/media/wysiwyg/1494578159_1487860495_kamila_3.jpg\&quot;,\&quot;mobile_image\&quot;:\&quot;https://magento2ee.test/pub/media/wysiwyg/uyze20435.00.0533_3.jpg\&quot;}"
                         data-element="wrapper"
                         style="background-position: left top; background-size: cover; background-repeat: repeat; border-width: 1px; border-radius: 99px; min-height: 450px; padding: 40px; text-align: right;">
                        <div class="pagebuilder-overlay" data-overlay-color="" data-element="overlay"
                             style="background-color: transparent;">
                            <div class="pagebuilder-collage-content">
                                <div data-element="content">
                                    <div><strong><span style="color: #ffffff;">sLIDE CONTENT</span></strong></div>
                                </div>
                                <button type="button" class="pagebuilder-slide-button pagebuilder-button-secondary"
                                        data-element="button" style="opacity: 1; visibility: visible;">
                                    sdsdsdsdsdsddddddddddd
                                </button>
                            </div>
                        </div>
                    </div>
                </a></div>
            <div data-content-type="slide" data-slide-name="" data-appearance="poster" data-show-button="always"
                 data-show-overlay="never" data-element="main" style="margin: 0px;">
                <div data-element="empty_link">
                    <div class="pagebuilder-slide-wrapper"
                         data-background-images="{\&quot;desktop_image\&quot;:\&quot;https://magento2ee.test/pub/media/wysiwyg/1529585052_okazje-banner_1.jpg\&quot;}"
                         data-element="wrapper"
                         style="background-position: left top; background-size: cover; background-repeat: no-repeat; border-style: none; border-width: 1px; border-radius: 0px; min-height: 300px;">
                        <div class="pagebuilder-overlay pagebuilder-poster-overlay" data-overlay-color=""
                             data-element="overlay"
                             style="min-height: 300px; padding: 40px; background-color: transparent;">
                            <div class="pagebuilder-poster-content">
                                <div data-element="content"></div>
                                <button type="button" class="pagebuilder-slide-button pagebuilder-button-primary"
                                        data-element="button" style="opacity: 1; visibility: visible;">button text
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div data-content-type="slide" data-slide-name="" data-appearance="poster" data-show-button="never"
                 data-show-overlay="never" data-element="main" style="margin: 0px;">
                <div data-element="empty_link">
                    <div class="pagebuilder-slide-wrapper"
                         data-background-images="{\&quot;desktop_image\&quot;:\&quot;https://magento2ee.test/pub/media/wysiwyg/1547204731_baner_oprawy.png\&quot;}"
                         data-element="wrapper"
                         style="background-position: left top; background-size: cover; background-repeat: no-repeat; border-style: none; border-width: 1px; border-radius: 0px; min-height: 300px;">
                        <div class="pagebuilder-overlay pagebuilder-poster-overlay" data-overlay-color=""
                             data-element="overlay"
                             style="min-height: 300px; padding: 40px; background-color: transparent;">
                            <div class="pagebuilder-poster-content">
                                <div data-element="content"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
